version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://172.17.0.1:4566
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    environment:
      - API_GATEWAY_ID=bn6z4q3kcg
    command: -f /mnt/locust/locustfile.py --worker --master-host master  
